general:
  general:
    backend: default
    imshow_origin: upper
    zoom_around_mask: true
  units:
    in_kpc: false
include:
  include_1d:
    einstein_radius: true
    half_light_radius: true
  include_2d:
    border: true
    tangential_caustics: true
    radial_caustics: true
    tangential_critical_curves: true
    radial_critical_curves: true
    grid: false
    light_profile_centres: true
    mapper_image_plane_mesh_grid: true
    mapper_source_plane_data_grid: false
    mapper_source_plane_mesh_grid: false
    mask: true
    mass_profile_centres: true
    multiple_images: false
    origin: false
    positions: true
mat_wrap:
  Axis:
    figure: {}
    subplot: {}
  Cmap:
    figure:
      cmap: default
      linscale: 0.01
      linthresh: 0.05
      norm: linear
      vmax: null
      vmin: null
    subplot:
      cmap: default
      linscale: 0.01
      linthresh: 0.05
      norm: linear
      vmax: null
      vmin: null
  Colorbar:
    figure:
      fraction: 0.047
      pad: 0.01
    subplot:
      fraction: 0.047
      pad: 0.01
  ColorbarTickParams:
    figure:
      labelsize: 10
    subplot:
      labelsize: 10
  Figure:
    figure:
      aspect: square
      figsize: (7,7)
    subplot:
      aspect: square
      figsize: auto
  Legend:
    figure:
      fontsize: 12
      include_2d: true
    subplot:
      fontsize: 12
      include_2d: true
  TickParams:
    figure:
      labelsize: 16
    subplot:
      labelsize: 10
  Title:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  XLabel:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  XTicks:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  YLabel:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  YTicks:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
mat_wrap_1d:
  EinsteinRadiusAXVLine:
    figure: {}
    subplot: {}
  HalfLightRadiusAXVLine:
    figure: {}
    subplot: {}
  YXPlot:
    figure:
      c: k
    subplot:
      c: k
mat_wrap_2d:
  ArrayOverlay:
    figure:
      alpha: 0.5
    subplot:
      alpha: 0.5
  BorderScatter:
    figure:
      c: r
      marker: .
      s: 30
    subplot:
      c: r
      marker: .
      s: 30
  CausticsPlot:
    figure:
      c: k,r,g,b,m,y
      linestyle: '-'
      linewidth: 2
    subplot:
      c: k,r,g,b,m,y
      linestyle: '-'
      linewidth: 2
  CriticalCurvesPlot:
    figure:
      c: k,r,g,b,m,y
      linestyle: '-'
      linewidth: 2
    subplot:
      c: k,r,g,b,m,y
      linestyle: '-'
      linewidth: 2
  GridPlot:
    figure:
      c: k
    subplot:
      c: k
  GridScatter:
    figure:
      c: k
      marker: .
      s: 1
    subplot:
      c: k
      marker: .
      s: 1
  IndexScatter:
    figure:
      c: r,g,b,m,y,k
      marker: .
      s: 20
    subplot:
      c: r,g,b,m,y,k
      marker: .
      s: 20
  LightProfileCentresScatter:
    figure:
      c: k,r,g,b,m,y
      marker: +
      s: 20
    subplot:
      c: r,g,b,m,y,k
      marker: +
      s: 26
  MaskScatter:
    figure:
      c: k
      marker: x
      s: 10
    subplot:
      c: k
      marker: x
      s: 10
  MassProfileCentresScatter:
    figure:
      c: k,r,g,b,m,y
      marker: x
      s: 20
    subplot:
      c: r,g,b,m,y,k
      marker: x
      s: 26
  MultipleImagesScatter:
    figure:
      c: k,r,g,b,m,y
      marker: o
      s: 16
    subplot:
      c: r,g,b,m,y,k
      marker: o
      s: 16
  OriginScatter:
    figure:
      c: k
      marker: x
      s: 80
    subplot:
      c: k
      marker: x
      s: 80
  PatchOverlay:
    figure:
      edgecolor: c
      facecolor: null
    subplot:
      edgecolor: c
      facecolor: null
  PixelizationGridScatter:
    figure:
      c: c
      marker: .
      s: 1
    subplot:
      c: c
      marker: .
      s: 1
  PositionsScatter:
    figure:
      c: k,m,y,b,r,g
      marker: '*'
      s: 80
    subplot:
      c: k,m,y,b,r,g
      marker: '*'
      s: 80
  VectorFieldQuiver:
    figure:
      alpha: 1.0
      angles: xy
      headlength: 0
      headwidth: 1
      linewidth: 5
      pivot: middle
      units: xy
    subplot:
      alpha: 1.0
      angles: xy
      headlength: 0
      headwidth: 1
      linewidth: 5
      pivot: middle
      units: xy
  VoronoiDrawer:
    figure:
      alpha: 0.7
      edgecolor: k
      linewidth: 0.3
    subplot:
      alpha: 0.7
      edgecolor: k
      linewidth: 0.3
plots:
  dataset:
    absolute_signal_to_noise_map: false
    data: false
    inverse_noise_map: false
    noise_map: false
    potential_chi_squared_map: false
    psf: false
    signal_to_noise_map: false
    subplot_dataset: false
    uv_wavelengths: false
  fit:
    all_at_end_fits: false
    all_at_end_png: false
    chi_squared_map: false
    data: false
    model_data: false
    model_images_of_planes: false
    noise_map: false
    normalized_residual_map: false
    plane_images_of_planes: false
    residual_map: false
    signal_to_noise_map: false
    subplot_fit: false
    subplots_of_planes: false
    subtracted_images_of_planes: false
  fit_quantity:
    all_at_end_fits: false
    all_at_end_png: false
    chi_squared_map: false
    image: false
    model_image: false
    noise_map: false
    normalized_residual_map: false
    residual_map: false
    subplot_fit: true
  adapt:
    contribution_map_list: falseadapt-
    images_of_galaxies: false
    model_image: false
  inversion:
    all_at_end_png: false
    chi_squared_map: false
    errors: false
    normalized_residual_map: false
    reconstructed_image: false
    reconstruction: false
    regularization_weights: false
    residual_map: false
    subplot_inversion: false
  other:
    stochastic_histogram: false
  positions:
    image_with_positions: true
  ray_tracing:
    all_at_end_fits: false
    all_at_end_png: false
    convergence: false
    deflections: false
    image: false
    magnification: false
    potential: false
    source_plane_image: false
    subplot_plane_images: false
    subplot_ray_tracing: false
  samples:
    corner: false
    progress: false
plots_search:
  dynesty:
    cornerplot: false
    cornerpoints: false
    runplot: false
    traceplot: false
  emcee:
    corner: false
    likelihood_series: false
    time_series: false
    trajectories: false
  pyswarms:
    contour: false
    cost_history: false
    time_series: false
    trajectories: false
  ultranest:
    cornerplot: false
    runplot: false
    traceplot: false
  zeus:
    corner: false
    likelihood_series: false
    time_series: false
    trajectories: false
